CREATE  TABLE GRISELA_CUSTOMER_VALIDATIONS
(
 
 CUSTOMER_VALIDATIONS_ID  NUMBER GENERATED BY DEFAULT AS IDENTITY,
 customer_type varchar2(150),
 customer_category varchar2(150),
 field_description varchar (155), 
 mandatory_validations varchar2(150),
 Constraint GRISELA_CUSTOMER_VALIDATIONS Primary key(CUSTOMER_VALIDATIONS_ID)
   

);
